# Generated by Django 5.1.7 on 2025-03-25 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='skills_teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users_with_skill', to='api.skill'),
        ),
        migrations.AlterField(
            model_name='scheduledsession',
            name='learn_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='api.skill'),
        ),
        migrations.AlterField(
            model_name='scheduledsession',
            name='teach_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to='api.skill'),
        ),
    ]
