# Generated by Django 5.1.7 on 2025-03-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_full_name_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
