# Generated by Django 5.1.7 on 2025-03-21 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_badge_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillmatch',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillmatch',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('skill_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.skillmatch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
